site_name: The Proxy Company
site_description: Technical Documentation for The Proxy Company's Technology
site_author: The Proxy Company
copyright: Copyright &copy; 2025 The Proxy Company

site_url: https://docs.theproxycompany.com/
repo_url: https://github.com/TheProxyCompany
repo_name: The Proxy Company
edit_uri: ""

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    # - navigation.sections
    # - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - palette.toggle
  logo: assets/proxy-p.svg
  favicon: assets/proxy-p.svg

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist
  - attr_list
  - md_in_html

extra:
  generator: false
  homepage: https://theproxycompany.com

extra_css:
  - assets/stylesheets/extra.css

nav:
  - Proxy Structuring Engine: /pse/
  - Proxy Base Agent: /pba/

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: false
      type: date
  - group:
      enabled: !ENV [CI, false]
      plugins:
        - projects
        - optimize
        - privacy
        - social:
            cards_layout_dir: layouts
            cards_layout: custom
            cards_layout_options:
              background_image: assets/tpc-logo.png
              background_color: transparent
              title: The Proxy Company
              description: The Proxy Company's Technical Documentation
              color: "#024645"

# For Vercel deployment
use_directory_urls: true
