site_name: The Proxy Company
site_description: Technical Documentation for The Proxy Company's Technology
site_author: The Proxy Company
copyright: Copyright &copy; 2025 The Proxy Company

repo_url: https://github.com/TheProxyCompany
repo_name: The Proxy Company
edit_uri: ""

theme:
  name: material
  palette:
    # Light mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.code.copy
    - palette.toggle
  logo: assets/proxy-p.svg
  favicon: assets/proxy-p.svg

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/TheProxyCompany
  homepage: https://theproxycompany.com

extra_css:
  - assets/stylesheets/extra.css

nav:
  - Home: index.md
  - About: about.md
  - Technology:
    - Proxy Structuring Engine: 
      - Overview: technology/pse.md
      - Detailed Documentation: /pse/
    - Proxy Base Agent: 
      - Overview: technology/pba.md
      - Detailed Documentation: /pba/
  - Research:
    - Proxy Structuring Engine: research/pse.md
    - Proxy Base Agent: research/pba.md
  - Resources:
    - Introduction:
      - Overview: introduction/overview.md
      - Key Features: introduction/key-features.md
      - Use Cases: introduction/use-cases.md
      - Comparison: introduction/comparison.md
    - Getting Started:
      - Installation: getting-started/installation.md
      - Quickstart: getting-started/quickstart.md
      - Basic Concepts: getting-started/basic-concepts.md
      - First Project: getting-started/first-project.md
    - Core Concepts:
      - State Machine: core-concepts/state-machine.md
      - Token Healing: core-concepts/token-healing.md
    - Guides:
      - JSON Schema: guides/json-schema.md
    - API Reference:
      - Structuring Engine: api/structuring-engine.md
      - Framework Adapters: api/framework-adapters.md
  - Contact: contact.md

plugins:
  - search

# For Vercel deployment
use_directory_urls: true
