site_name: The Proxy Company
site_description: Technical Documentation for The Proxy Company's Technology
site_author: The Proxy Company
copyright: Copyright &copy; 2025 The Proxy Company

site_url: https://docs.theproxycompany.com/
repo_url: https://github.com/TheProxyCompany
repo_name: The Proxy Company
edit_uri: ""

theme:
  name: material
  palette:
    # Light mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.code.copy
    - palette.toggle
  logo: assets/proxy-p.svg
  favicon: assets/proxy-p.svg

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist
  - attr_list
  - md_in_html

extra:
  generator: false
  homepage: https://docs.theproxycompany.com

extra_css:
  - assets/stylesheets/extra.css

nav:
  - Home: index.md
  - Proxy Structuring Engine: /pse/
  - Proxy Base Agent: /pba/

plugins:
  - search
  - social:
      cards_layout_options:
        background_image: assets/tpc-logo.png
        title: The Proxy Company
        description: Comprehensive technical documentation for The Proxy Company's Technology
        logo: assets/proxy-p.svg
  - sitemap:
      sitemap_url: https://docs.theproxycompany.com/

# For Vercel deployment
use_directory_urls: true
