site_name: PSE Documentation
site_description: Comprehensive technical documentation for the Proxy Structuring Engine (PSE)
site_author: The Proxy Company
copyright: Copyright &copy; 2025 The Proxy Company

site_url: https://docs.theproxycompany.com/pse/
repo_url: https://github.com/TheProxyCompany/proxy-structuring-engine
repo_name: Proxy Structuring Engine
edit_uri: ""

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - palette.toggle
    - toc.integrate
  logo: ../assets/proxy-p.svg
  favicon: ../assets/proxy-p.svg

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  generator: false
  homepage: https://docs.theproxycompany.com/

extra_css:
  - ../assets/stylesheets/extra.css

nav:
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quickstart: getting-started/quickstart.md

  - Core Concepts:
    # - State Machine Architecture: core-concepts/state-machine.md
    # - Core Architecture: core-concepts/core-architecture.md
    - State Graph Traversal Algorithm: core-concepts/state-graph-traversal.md
    # - Stepper System: core-concepts/stepper.md
    # - Token Healing: core-concepts/token-healing.md
    # - Multi-Token Processing: core-concepts/multi-token-processing.md

  - API Reference:
    - State Machines:
      - Base State Machines: api/state-machines/base.md
      - Data Type State Machines: api/state-machines/datatypes.md
      - Format-Specific State Machines: api/state-machines/formats.md
      - Schema Sources: api/state-machines/schema-sources.md

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: false
      type: date
  - group:
      enabled: !ENV [CI, false]
      plugins:
        - optimize
        - privacy
        - social:
            cards_layout_dir: ../layouts
            cards_layout: custom
            cards_layout_options:
              background_image: ../assets/pse-logo.png
              background_color: transparent
              title: Proxy Structuring Engine
              description: Technical Documentation for the Proxy Structuring Engine
              color: "#024645"

# For Vercel deployment
use_directory_urls: true
