site_name: Proxy Base Agent
site_description: A stateful, tool-enabled agent built with the Proxy Structuring Engine.
site_url: https://docs.theproxy.company/pba/ # Update with the correct URL
repo_url: https://github.com/TheProxyCompany/agent # Assuming this is the correct repo
repo_name: TheProxyCompany/agent
edit_uri: ""

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: indigo
      accent: indigo
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: indigo
      accent: indigo
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quickstart: getting-started/quickstart.md
  - Concepts:
    - Overview: concepts/overview.md
    - State Machine: concepts/state-machine.md
    - Tools: concepts/tools.md
  - Extending the Agent:
    - Custom Tools: extending/custom-tools.md
    - Custom States: extending/custom-states.md
  - API Reference:
    - Agent: api/agent.md
    - State Machine: api/state_machine.md
    - Tools: api/tools.md
  - Contributing: contributing.md
  - License: license.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - toc:
      permalink: true
  - codehilite:
      guess_lang: false
  - footnotes
  - meta

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/TheProxyCompany
      name: The Proxy Company on GitHub

# For Vercel deployment
use_directory_urls: true
