site_name: Proxy Base Agent
site_description: A stateful, tool-enabled agent built with the Proxy Structuring Engine.
site_author: The Proxy Company
copyright: Copyright &copy; 2025 The Proxy Company

site_url: https://docs.theproxycompany.com/pba/
repo_url: https://github.com/TheProxyCompany/proxy-base-agent
repo_name: Proxy Base Agent
edit_uri: ""

theme:
  name: material
  palette:
    # Light mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.code.copy
    - palette.toggle
  logo: assets/proxy-p.svg
  favicon: assets/proxy-p.svg

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quickstart: getting-started/quickstart.md
  - Concepts:
    - Overview: concepts/overview.md
    - State Graph: concepts/state-graph.md
    - States: concepts/states.md
    - Tools: concepts/tools.md
    - State Machine: concepts/state-machine.md
  - Extending the Agent:
    - Custom Tools: extending/custom-tools.md
    - Custom States: extending/custom-states.md
    - Custom State Graphs: extending/custom-state-graphs.md
    - Model Context Protocol: extending/model-context-protocol.md
  - Running the Agent:
    - MLX: frontends/mlx.md
    - PyTorch: frontends/pytorch.md
  - API Reference:
    - Agent: api/agent.md

extra:
  generator: false
  homepage: https://docs.theproxycompany.com/pba/

plugins:
  - search
  - group:
      enabled: !ENV [CI, false]
      plugins:
        - optimize
        - privacy
        - social:
            cards_layout_dir: ../layouts
            cards_layout: custom
            cards_layout_options:
              background_image: ../assets/pba-logo.png
              background_color: transparent
              title: Proxy Base Agent
              description: Technical Documentation for the Proxy Base Agent
              color: "#035a59"

extra_css:
  - assets/stylesheets/extra.css

# For Vercel deployment
use_directory_urls: true
