site_name: Proxy Base Agent Documentation
site_description: Comprehensive technical documentation for the Proxy Base Agent (PBA)
site_author: The Proxy Company
copyright: Copyright &copy; 2025 The Proxy Company

repo_url: https://github.com/TheProxyCompany/proxy-base-agent
edit_uri: ""

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.code.copy
  logo: assets/proxy-p.svg
  favicon: assets/proxy-p.svg

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist
  - attr_list
  - md_in_html

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/TheProxyCompany/proxy-base-agent
  homepage: https://docs.theproxycompany.com

extra_css:
  - assets/stylesheets/extra.css

nav:
  - Home: index.md
  - Introduction:
    - Overview: introduction/overview.md
    - Key Features: introduction/key-features.md
    - Use Cases: introduction/use-cases.md
  
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quickstart: getting-started/quickstart.md
    - Configuration: getting-started/configuration.md
  
  - Core Concepts:
    - Agent Architecture: core-concepts/architecture.md
    - Tool Integration: core-concepts/tool-integration.md
    - Memory & Context: core-concepts/memory.md
    - Planning & Reasoning: core-concepts/planning.md
  
  - User Guides:
    - Building Custom Tools: guides/custom-tools.md
    - Multi-Agent Systems: guides/multi-agent.md
    - Interactive Applications: guides/interactive-apps.md
    - Error Handling: guides/error-handling.md
    - Performance Optimization: guides/performance.md
  
  - API Reference:
    - Agent: api/agent.md
    - Tool Registry: api/tool-registry.md
    - Memory Interface: api/memory.md
  
  - Advanced Topics:
    - Benchmarks and Metrics: advanced/benchmarks.md
    - Orchestration: advanced/orchestration.md
    - Security Considerations: advanced/security.md
    - Enterprise Integration: advanced/enterprise-integration.md
  
  - Tutorials:
    - Data Analysis Agent: tutorials/data-analysis.md
    - Customer Support Agent: tutorials/customer-support.md
    - Creative Writing Assistant: tutorials/writing-assistant.md
  
  - Development:
    - Contributing Guide: development/contributing.md
    - Testing: development/testing.md
    - Development Setup: development/setup.md
    - Project Architecture: development/architecture.md
    - Release Process: development/release-process.md
  
  - Resources:
    - FAQ: resources/faq.md
    - Troubleshooting: resources/troubleshooting.md
    - Community: resources/community.md
    - Roadmap: resources/roadmap.md
    - Change Log: resources/changelog.md
  
  - Back to Main Site: https://docs.theproxycompany.com

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: google

# For Vercel deployment
use_directory_urls: true