site_name: Proxy Base Agent
site_description: A stateful, tool-enabled agent built with the Proxy Structuring Engine.
site_author: The Proxy Company
copyright: Copyright &copy; 2025 The Proxy Company

repo_url: https://github.com/TheProxyCompany/proxy-base-agent
repo_name: Proxy Base Agent
edit_uri: ""

theme:
  name: material
  palette:
    # Light mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.code.copy
    - palette.toggle
  logo: assets/proxy-p.svg
  favicon: assets/proxy-p.svg

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist
  - attr_list
  - md_in_html

plugins:
  - search

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quickstart: getting-started/quickstart.md
  - Concepts:
    - Overview: concepts/overview.md
    - State Machine: concepts/state-machine.md
    - Tools: concepts/tools.md
  - Extending the Agent:
    - Custom Tools: extending/custom-tools.md
    - Custom States: extending/custom-states.md
  - API Reference:
    - Agent: api/agent.md

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/TheProxyCompany/proxy-base-agent
  homepage: https://docs.theproxycompany.com

extra_css:
  - assets/stylesheets/extra.css

# For Vercel deployment
use_directory_urls: true
